# Importing Libraries

In [1]:
npm i jupyter-js-widget

SyntaxError: invalid syntax (2082559963.py, line 1)

[vectors-matrices](https://www.mathsisfun.com/algebra/matrix-introduction.html)

NumPy Python Standard Library içerisinde bulunan bir module değildir.

NumPy module'unu import etmek için önce ; NumPy module'unu Python pip aracı ile install etmemiz gerekiyor.

"pip" aracı bize Standard Library'de bulunmayan module'leri/package'leri dışarıdan install etmeyi sağlar.

In [10]:
#pip install numpy

In [1]:
jupyter nbextension install --sys-prefix --symlink --overwrite --py pydeck

SyntaxError: invalid syntax (1570541252.py, line 1)

In [2]:
import numpy as np

# Create Array Methods

[numpy source 01](https://stackabuse.com/numpy-tutorial-a-simple-example-based-guide/),
[numpy source 02](https://sparkbyexamples.com/numpy/ways-to-create-numpy-array/),
[numpy source 03](https://www.freecodecamp.org/news/the-ultimate-guide-to-the-numpy-scientific-computing-library-for-python/)

## From a Python List

### resize

resize(), ndarray nesnesinin boyutunu yeniden şekillendirmek için kullanılır. 

Bu yöntem, ndarray nesnesinin boyutunu değiştirir ve yeni boyutlara uygun olarak verileri değiştirir. 

Yani, ndarray nesnesinin boyutunu değiştirmek ve verilerini yeniden boyutlandırmak istediğinizde, resize yöntemini kullanabilirsiniz. 

Ancak, bu işlem, orijinal verilerin değiştirilmesine neden olabilir, bu nedenle dikkatli kullanılmalıdır.

In [3]:
arr = np.array([[1,2,3],[4,5,6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.resize(arr,(6,3))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [11]:
np.resize(arr,(2,2))

array([[1, 2],
       [3, 4]])

In [9]:
np.reshape(arr,(6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### fromiter

In [16]:
my_iter = (i for i in range(5))
my_iter

<generator object <genexpr> at 0x000001D410C22500>

In [19]:
np.fromiter(my_iter, int) # dtype girmemiz gerekiyor

array([], dtype=int32)

In [20]:
np.fromiter(my_iter, float) # dtype girmemiz gerekiyor

array([], dtype=float64)

fromiter(), bir array oluşturmak için bir iterator nesnesinden verileri alır.

Verilerin bellekte tutulmasına gerek kalmadan, yineleyiciden elemanları tek tek çekerek NumPy dizisine dönüştürür. 

Bu özellikle büyük verilerle çalışırken bellek kullanımını azaltmak için yararlıdır.

## From Built-in Methods

### arange

Python’daki range() fonksiyonuna benzer. 

Belirtilen başlangıç değerinden başlayıp, her seferinde adım sayısı kadar arttırarak ,bitiş değerine kadar olan sayıları bulunduran bir numpy dizisi dödürür.

Not: Bitiş değerinin diziye dahil edilmediğine dikkat edelim.

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [24]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [29]:
np.arange(1,10,-1)

array([], dtype=int32)

In [27]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [152]:
list(arr)

[array([42, 42, 42, 42]), array([4, 5, 6, 7]), array([12, 12, 12, 12])]

In [153]:
arr.list()

AttributeError: 'numpy.ndarray' object has no attribute 'list'

In [154]:
list.array()

AttributeError: type object 'list' has no attribute 'array'

### linspace

Verilen başlangıç ve bitiş değerleri arasında, belirtilen sayıda eşit aralıklı değerlerden oluşan bir numpy dizisi oluşturur.

Bu fonksiyon, özellikle grafik çizme ve veri analizi gibi durumlarda yararlıdır.


In [31]:
np.linspace(1,20) # bölme işlemi her zaman float döner

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [32]:
np.linspace(1,20, num=10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [33]:
np.linspace(1,20, 10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [35]:
np.linspace(1,20, 10, endpoint=False)

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1])

In [34]:
np.linspace(1,20, 10, dtype=int)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 20])

In [36]:
np.linspace(1,20, 10, retstep=True)

(array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
        11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ]),
 2.111111111111111)

In [38]:
np.linspace(1,[10,20], 5, axis=1) # 1,den 10 kadar 5 adet 1. axis'e ata
                                  # 1,den 20 kadar 5 adet 1. axis'e ata

array([[ 1.  ,  3.25,  5.5 ,  7.75, 10.  ],
       [ 1.  ,  5.75, 10.5 , 15.25, 20.  ]])

In [39]:
np.linspace(0,[10,20], 5, axis=0) # 1,den 10 kadar 5 adet 0. axis'e ata
                                  # 1,den 20 kadar 5 adet 0. axis'e ata

array([[ 0. ,  0. ],
       [ 2.5,  5. ],
       [ 5. , 10. ],
       [ 7.5, 15. ],
       [10. , 20. ]])

### logspace

logspace() logaritmik aralıklarda bir dizi oluşturur. 

logspace() fonksiyonu, linspace() fonksiyonuna benzer şekilde çalışır, ancak aralıklar logaritmik olarak hesaplanır.

Logspace : Başlangıç değeri 10a ,bitiş değeri değeri 10b olan n elemanlı ve elemanları arasındaki katları eşit olan bir dizi oluşturur.


In [42]:
np.logspace(2,3,5, dtype=float)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

### zeros, zeros_like
Belirtilen satır ve sütuna sahip 0'lardan oluşan bir matris döndürür.

In [46]:
np.zeros(3)

array([0., 0., 0.])

In [49]:
np.zeros(3,3)

TypeError: Cannot interpret '3' as a data type

In [50]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.zeros([3,3], dtype= bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [53]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
np.zeros_like(arr)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### ones
Belirtilen satır ve sütuna sahip 1'lerdan oluşan bir matris döndürür.

In [59]:
np.ones([3,4], dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
np.ones((3,4), dtype=float) * 55

array([[55., 55., 55., 55.],
       [55., 55., 55., 55.],
       [55., 55., 55., 55.]])

In [62]:
np.ones_like(arr)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### eye
Belirlenen boyutlarda birim matris oluşturmamızı sağlayan fonksiyon.

In [64]:
np.eye(3,3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [65]:
np.eye(3,3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

### full
Sabit sayıdan oluşan matris oluşturur

In [71]:
np.full((2,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [73]:
np.full_like(arr, 2, dtype=float)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

# Various Built-in Methods

## rand

random.rand(), 0-1 aralığında random float sayılar üretir.

In [74]:
np.random.rand(3,3)

array([[0.75104743, 0.59832873, 0.52938379],
       [0.53471428, 0.70679396, 0.6072877 ],
       [0.21047732, 0.77185013, 0.21128488]])

In [85]:
pip install matplotlib

     ---------------------------------------- 7.6/7.6 MB 1.8 MB/s eta 0:00:00
     ---------------------------------------- 55.3/55.3 kB 1.5 MB/s eta 0:00:00
     -------------------------------------- 163.0/163.0 kB 1.4 MB/s eta 0:00:00
     -------------------------------------- 98.3/98.3 kB 704.8 kB/s eta 0:00:00
     ---------------------------------------- 1.0/1.0 MB 1.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [86]:
import matplotlib.pyplot as plt

## randn

random.randn(), ortalama değeri 0 ve standart sapması 1 olan normal dağılıma sahip rastgele sayılar üretmek için kullanılır. 

Fonksiyon, normal dağılımdan rastgele sayılar üretir ve bu sayıları NumPy dizisi olarak döndürür.

In [87]:
np.random.randn(3,4)

array([[ 1.34584779,  0.07099598, -0.76055135,  0.77742051],
       [ 0.11367243,  0.7542161 ,  0.27859412,  0.22694144],
       [ 0.36511749, -1.22802996,  0.15285918,  0.20170232]])

## randint

random.randint(), 0-100 aralığında integer değerler üretir

Bitiş(100) dahil değil

In [102]:
np.random.randint(10,50, size=10).reshape(2,5)

array([[40, 49, 37, 38, 46],
       [45, 47, 18, 48, 14]])

In [104]:
np.random.randint(10,50, size=(2,5))

array([[44, 39, 22, 37, 35],
       [23, 49, 36, 14, 41]])

In [105]:
np.random.randint(10,50, size=(5,5))

array([[34, 11, 34, 12, 17],
       [32, 17, 48, 11, 25],
       [25, 40, 38, 31, 25],
       [33, 19, 30, 22, 36],
       [35, 17, 48, 30, 20]])

In [94]:
np.random.randint(10)

3

In [101]:
np.random.randint(98,100)

98

## max & argmax & min & argmin

min(), bir dizinin içindeki en küçük değeri döndürür

max(), bir dizinin içindeki en büyük değeri döndürür

argmin(), bir dizinin içindeki en küçük değerin indeksini döndürür

argmax(), bir dizinin içindeki en büyük değerin indeksini döndürür

In [112]:
my_array = np.random.randint(0,50,10)
my_array

array([ 0, 46, 23, 13, 13, 15, 20, 21, 21, 23])

In [113]:
my_array.max()

46

In [114]:
my_array.argmax() # indeksi getirir

1

In [115]:
my_array.min()

0

In [116]:
my_array.argmin()

0

## ndim

In [117]:
arr.ndim # ndmin istedigin boyuta ceviriyor, ndim ise kac boyutlu oldugunu veriyor


2

In [118]:
my_array.ndim

1

## size
Bir dizideki toplam eleman sayısı

2x3'lük bir matris için size=6

In [119]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [120]:
arr.size

12

In [121]:
arr.shape

(4, 3)

In [122]:
len(arr) #

4

In [129]:
arr.resize(3,4,1)
arr

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [137]:
arr.resize(3,4,1)
len(arr)

3

## itemsize

itemsize(), NumPy dizisinin her bir elemanının bellekte kaç byte kapladığını gösterir. 

Bu özellik, NumPy dizisinin veri tipine (dtype) bağlıdır ve bu veri tipinin boyutuna göre değişir.

itemsize(), bir NumPy dizisinin bellekte kapladığı toplam alanı hesaplamak için de kullanılabilir. Bu hesaplama, dizinin eleman sayısının itemsize() ile çarpımı ile yapılabilir.

float32 tipi 32 bit (4 byte) bellek kullanır ve yaklaşık 7 basamak hassasiyetle ondalık sayıları temsil edebilir. 

32 bitlik bir sayı, 2^32 farklı sayıyı ifade edebilir.

float64 tipi ise 64 bit (8 byte) bellek kullanır ve yaklaşık 15-16 basamak hassasiyetle ondalık sayıları temsil edebilir

64 bitlik bir sayı, 2^64 farklı sayıyı ifade edebilir.

In [130]:
arr.dtype

dtype('int32')

In [133]:
arr.itemsize

4

In [134]:
arr.itemsize * 4

16

In [135]:
arr.itemsize * arr.size

48

## copy

copy(), Numpy dizilerinde bir kopya oluşturmak için kullanılır. 

Bu fonksiyon, orijinal dizinin aynısını oluşturur ancak bu kopya bağımsızdır. Yani, kopya dizisi üzerinde yapılan herhangi bir değişiklik, orijinal diziyi etkilemez ve orijinal dizi üzerinde yapılan değişiklikler de kopya dizisini etkilemez.

In [140]:
arr.resize(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [144]:
x = arr.copy()
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [146]:
arr[0] = 42
arr

array([[42, 42, 42, 42],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
arr[2] = 12
arr

array([[42, 42, 42, 42],
       [ 4,  5,  6,  7],
       [12, 12, 12, 12]])

In [148]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## transpose

transpose() fonksiyonu, NumPy dizilerinin boyutlarını değiştiren bir işlevdir. Özellikle matrislerin transpozunu almak için kullanılır.

Bir matrisin transpozunu almak, matrisin satırlarını sütunlarına, sütunlarını da satırlarına dönüştürür.

In [150]:
arr.transpose()

array([[42,  4, 12],
       [42,  5, 12],
       [42,  6, 12],
       [42,  7, 12]])

In [151]:
x.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# Concatenation of the Arrays

[numpy.concatenate 01](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html),
[numpy.concatenate 02](https://sparkbyexamples.com/numpy/numpy-concatenate-arrays/),
[numpy.concatenate 03](https://www.tutorialspoint.com/numpy/numpy_concatenate.htm),
[numpy.concatenate 04](https://www.w3resource.com/numpy/manipulation/concatenate.php)

concatenate() fonksiyonu, iki veya daha fazla diziyi birleştirmek için kullanılır. 

Fonksiyonun ilk parametresi birleştirilecek dizilerin bir listesidir. 

İkinci parametre ise, birleştirme işleminin hangi eksen veya boyuta göre yapılacağını belirten bir parametredir.

Örneğin, axis=0 parametresi, dizilerin satır bazında (dikey birleştirme) birleştirilmesini, axis=1 parametresi ise sütun bazında (yatay birleştirme) birleştirilmesini sağlar.

# Splitting of the Arrays

[numpy.split 01](https://www.w3resource.com/numpy/manipulation/split.php),
[numpy.split 02](https://sparkbyexamples.com/numpy/numpy-split-array/),
[numpy.split 03](https://numpy.org/doc/stable/reference/generated/numpy.array_split.html),
[numpy.split 04](https://www.w3schools.com/python/numpy/numpy_array_split.asp)

split(), numpy dizisini belirtilen eksende eşit parçalara bölmek için kullanılır.

# Sorting of the Arrays

[numpy.sort 01](https://www.w3schools.com/python/numpy/numpy_array_sort.asp),
[numpy.sort 02](https://sparkbyexamples.com/python/numpy-sort-arrays-examples/),
[numpy.sort 03](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sort.html),
[numpy.sort 04](https://www.geeksforgeeks.org/how-to-sort-a-numpy-array-python/)

sort(), numerik ya da alfabetik array elemanlarını, numerik veya alfabetik sıralarına göre sıralamasını yapar.